project:
  type: website
  output-dir: docs

website:
  title: "Viswadutt"
  site-url: https://viswaduttp.github.io/
  description: "Welcome to Viswadutt's Personal Page."
  navbar:
    right:
      - text: Blog
        href: blog.qmd 
      - icon: github
        href: https://github.com/viswaduttp
      - icon: twitter
        href: https://twitter.com/viswadutt
format:
  html:
    theme: cosmo
    css: styles.css
execute:
  freeze: auto

